# Model configuration
model_name_or_path: "Qwen/Qwen2.5-0.5B-Instruct"

# Dataset configuration
dataset_path: "data/debug_train.jsonl"

# Training configuration
training_args:
  output_dir: "./outputs"
  eval_strategy: "epoch"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  learning_rate: 5.0e-5
  num_train_epochs: 3.0
  lr_scheduler_type: "linear"
  warmup_ratio: 0.0
  logging_strategy: "epoch"
  save_strategy: "epoch"
  report_to: "all"

# Response template for data collator
response_template: " ### Answer:"
